import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement, useEffect } from "react";
import { useDispatch } from "react-redux";
import TelegramLoginButton from "../components/TelegramLoginButton";
import { setUser } from "../features/authSlice";
import { useAuth } from "../hooks/use-auth";

const Home: NextPage = () => {
  const authState = useAuth();
  const dispatch = useDispatch();
  const onTelegramAuth = (user: any) => {
    dispatch(setUser(user));
  };

  // useEffect(() => {
  //   // @ts-ignore
  //   window.onTelegramAuth = (user) => onTelegramAuth(user);
  // }, []);
  // const login = {
  //   __html: `<script async src="https://telegram.org/js/telegram-widget.js?19" data-telegram-login="ckdaycounter_bot" data-size="large" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
  //   <script type="text/javascript">
  //     // function onTelegramAuth(user) {
  //     //   alert('Logged in as ' + user.first_name + ' ' + user.last_name + ' (' + user.id + (user.username ? ', @' + user.username : '') + ')');
  //     // }
  //   </script>`,
  // };

  return (
    <div>
      <Head>
        <title>Login | Telegram Group Management App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full min-h-screen flex flex-col justify-center items-center text-center">
        <h1>Telegram Group Management App</h1>
        {/* <div dangerouslySetInnerHTML={login}></div> */}
        <hr></hr>
        <TelegramLoginButton
          botName="ckdaycounter_bot"
          dataOnauth={onTelegramAuth}
        />

        <pre>{authState?.username ?? "not logged in"}</pre>
      </main>
    </div>
  );
};

// @ts-ignore
Home.getLayout = function getLayout(page: ReactElement) {
  return page;
};

export default Home;
