import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";

const Home: NextPage = () => {
  const onTelegramAuth = (user: any) => {
    console.log(user);
  };
  const login = {
    __html: `<script async src="https://telegram.org/js/telegram-widget.js?19" data-telegram-login="ckdaycounter_bot" data-size="large" data-onauth="${(
      user: any
    ) => onTelegramAuth(user)}" data-request-access="write"></script>
    <script type="text/javascript">
      function onTelegramAuth(user) {
        alert('Logged in as ' + user.first_name + ' ' + user.last_name + ' (' + user.id + (user.username ? ', @' + user.username : '') + ')');
      }
    </script>`,
  };

  return (
    <div>
      <Head>
        <title>Login | Telegram Group Management App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full min-h-screen flex flex-col justify-center items-center text-center">
        <h1>Telegram Group Management App</h1>
        <div dangerouslySetInnerHTML={login}></div>
      </main>
    </div>
  );
};

// @ts-ignore
Home.getLayout = function getLayout(page: ReactElement) {
  return page;
};

export default Home;
